version: '3.1'
services:
  web:
    image: node:latest
    command: ['npm', 'run','watch']
    ports:
      - "30022:3101"
    depends_on:
      - db
    volumes:
      - .:/Users/artem/code/Signum/sygnum-owl-back
    working_dir: /Users/artem/code/Signum/sygnum-owl-back
  db:
    image: mysql:5.7
    ports:
      - "33036:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: sygnum_u
      MYSQL_DATABASE: sygnum_db
